#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# DualSub — EC2 Setup Script
# Run once on a fresh EC2 instance to configure and start the app.
# Usage: bash setup-ec2.sh [--groq-key YOUR_KEY] [--deepl-key YOUR_KEY]
# ─────────────────────────────────────────────────────────────────────────────

set -e

# ── Parse optional CLI flags ──────────────────────────────────────────────────
GROQ_KEY=""
DEEPL_KEY=""

while [[ "$#" -gt 0 ]]; do
  case $1 in
    --groq-key)  GROQ_KEY="$2";  shift ;;
    --deepl-key) DEEPL_KEY="$2"; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
  shift
done

# ── Auto-detect public IP ─────────────────────────────────────────────────────
echo "🔍 Detecting public IP..."

# Try EC2 metadata service first (works on AWS), fallback to external service
PUBLIC_IP=$(curl -s --connect-timeout 3 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null \
  || curl -s --connect-timeout 5 https://api.ipify.org \
  || curl -s --connect-timeout 5 https://ifconfig.me \
  || echo "")

if [ -z "$PUBLIC_IP" ]; then
  echo "⚠️  Could not auto-detect public IP. Please enter it manually:"
  read -r PUBLIC_IP
fi

echo "✅ Public IP: $PUBLIC_IP"

# ── Write .env file for docker-compose substitution ──────────────────────────
ENV_FILE=".env"

cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-ec2.sh on $(date)
# Re-run setup-ec2.sh to regenerate.

ALLOWED_ORIGIN=http://${PUBLIC_IP}:3001,http://localhost:3001

EOF

# Append optional keys if provided
if [ -n "$GROQ_KEY" ]; then
  echo "GROQ_API_KEY=${GROQ_KEY}" >> "$ENV_FILE"
fi
if [ -n "$DEEPL_KEY" ]; then
  echo "DEEPL_KEY=${DEEPL_KEY}" >> "$ENV_FILE"
fi

echo "✅ Written $ENV_FILE:"
cat "$ENV_FILE"

# ── Patch docker-compose.yml to inject optional keys as env vars ──────────────
# (Only if keys were provided — avoids overwriting manually set values)
if [ -n "$GROQ_KEY" ] && ! grep -q "GROQ_API_KEY" docker-compose.yml; then
  sed -i "s|DEEPL_KEY=.*|DEEPL_KEY=${DEEPL_KEY:-your-deepl-api-key-here}\n      - GROQ_API_KEY=${GROQ_KEY}|" docker-compose.yml
fi

# ── Ensure Docker is running ──────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "❌ Docker not found. Install Docker first: https://docs.docker.com/engine/install/"
  exit 1
fi

# ── Stop any existing container ───────────────────────────────────────────────
echo ""
echo "🛑 Stopping existing container (if any)..."
docker compose down --remove-orphans 2>/dev/null || true

# ── Build and start ───────────────────────────────────────────────────────────
echo ""
echo "🔨 Building and starting DualSub..."
docker compose up -d --build

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 DualSub is running!"
echo ""
echo "   Local:   http://localhost:3001"
echo "   Public:  http://${PUBLIC_IP}:3001"
echo ""
echo "   Make sure port 3001 is open in your EC2 Security Group."
echo ""
echo "   Logs:    docker logs dualsub-app -f"
echo "   Stop:    docker compose down"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
