#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# DualSub — EC2 Setup Script
# Run once on a fresh EC2 instance to configure and start the app.
# Usage: bash setup-ec2.sh [--groq-key YOUR_KEY] [--deepl-key YOUR_KEY]
# ─────────────────────────────────────────────────────────────────────────────

set -e

# ── Parse optional CLI flags ──────────────────────────────────────────────────
GROQ_KEY=""
DEEPL_KEY=""

while [[ "$#" -gt 0 ]]; do
  case $1 in
    --groq-key)  GROQ_KEY="$2";  shift ;;
    --deepl-key) DEEPL_KEY="$2"; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
  shift
done

# ── Detect docker-compose command (v1 vs v2) ─────────────────────────────────
if docker compose version &>/dev/null 2>&1; then
  COMPOSE_CMD="docker compose"
  echo "✅ Using Docker Compose V2 (docker compose)"
elif command -v docker-compose &>/dev/null; then
  COMPOSE_CMD="docker-compose"
  echo "✅ Using Docker Compose V1 (docker-compose)"
else
  echo "❌ docker-compose not found. Install it:"
  echo "   sudo apt-get install -y docker-compose"
  exit 1
fi

# ── Auto-detect public IP ─────────────────────────────────────────────────────
echo "🔍 Detecting public IP..."

PUBLIC_IP=""

# Try EC2 IMDSv2 (token-based — required on modern EC2 instances)
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" \
  --connect-timeout 2 2>/dev/null || echo "")

if [ -n "$TOKEN" ]; then
  PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
    http://169.254.169.254/latest/meta-data/public-ipv4 \
    --connect-timeout 2 2>/dev/null || echo "")
fi

# Fallback to external HTTP services
if [ -z "$PUBLIC_IP" ]; then
  PUBLIC_IP=$(curl -s --connect-timeout 5 https://ifconfig.me 2>/dev/null || echo "")
fi
if [ -z "$PUBLIC_IP" ]; then
  PUBLIC_IP=$(curl -s --connect-timeout 5 https://api.ipify.org 2>/dev/null || echo "")
fi

# Manual fallback
if [ -z "$PUBLIC_IP" ]; then
  echo "⚠️  Could not auto-detect public IP. Please enter it manually:"
  read -r PUBLIC_IP
fi

echo "✅ Public IP: $PUBLIC_IP"

# ── Write .env file for docker-compose variable substitution ─────────────────
ENV_FILE=".env"

cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-ec2.sh on $(date)
# Re-run setup-ec2.sh to regenerate.

ALLOWED_ORIGIN=http://${PUBLIC_IP}:3001,http://localhost:3001
EOF

# Append optional API keys if provided
if [ -n "$GROQ_KEY" ]; then
  echo "GROQ_API_KEY=${GROQ_KEY}" >> "$ENV_FILE"
fi
if [ -n "$DEEPL_KEY" ]; then
  echo "DEEPL_KEY=${DEEPL_KEY}" >> "$ENV_FILE"
fi

echo "✅ Written $ENV_FILE:"
cat "$ENV_FILE"

# ── Ensure Docker is installed ────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "❌ Docker not found. Install: https://docs.docker.com/engine/install/"
  exit 1
fi

# ── Stop any existing container ───────────────────────────────────────────────
echo ""
echo "🛑 Stopping existing container (if any)..."
$COMPOSE_CMD down --remove-orphans 2>/dev/null || true

# ── Build and start ───────────────────────────────────────────────────────────
echo ""
echo "🔨 Building and starting DualSub..."
$COMPOSE_CMD up -d --build

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 DualSub is running!"
echo ""
echo "   Local:   http://localhost:3001"
echo "   Public:  http://${PUBLIC_IP}:3001"
echo ""
echo "   ⚠️  Make sure port 3001 is open in your EC2 Security Group."
echo ""
echo "   Logs:    docker logs dualsub-app -f"
echo "   Stop:    $COMPOSE_CMD down"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
